level-cost: 3
wand-item: "minecraft:blaze_rod"

# Default: All animals are capturable
allowed-egg-ids: [ 65, 93, 101, 92, 98, 100, 96, 90, 91, 94, 95, ]

# 50  Creeper
# 58  Enderman
# 67  Endermite
# 56  Ghast
# 66  Witch
# 59  Cavespider
# 61  Blaze
# 62  Magmaslime
# 55  Slime
# 69  Shulker
# 60  Silverfish
# 51  Skeleton
# 52  Spider
# 68  Guardian
# 54  Zombie
# 57  Zombie Pigman

# 65  Bat
# 93  Chicken
# 101 Rabbit
# 92  Cow
# 98  Ocelot
# 100 Horse
# 96  Mooshroom
# 90  Pig
# 91  Sheep
# 94  Squid
# 95  Wolf

# 120 Villager
