# delay (in ticks) before setting time again
task-delay: 60

# set time in this worlds
worlds: []

# use null for default system timezone
timezone: null

# type "simple" correlates real time and minecraft time
# type "complex" calculates the minecraft times for real
# sunrise and sunset and interpolates the minecraft time inbetween
correlator-type: simple
