name: ${project.name}
author: teamalpha5441
version: ${project.version}
description: ${project.description}
main: ${project.groupId}.${project.name}

permissions:
  takeeplevels.keep:
    description: Allows you to keep your EXP levels on death