# Level cost, 0 to disable
cost:
  merge: 0
  extract: 0

# Level limits (uncomment for no limit)
# Enchantments with system limits do not improve with higher levels
level_limits:
  protection: 10
  fire_protection: 10
  feather_falling: 10
  blast_protection: 10
  projectile_protection: 10
  respiration: 3 # System limit
  aqua_affinity: 1 # System limit
  thorns: 5
  depth_strider: 3 # System limit
  frost_walker: 5
  sharpness: 10
  smite: 10
  bane_of_arthropods: 10
  knockback: 3
  fire_aspect: 3
  looting: 5
  efficiency: 10
  silk_touch: 1 # System limit
  unbreaking: 10
  fortune: 5
  power: 10
  punch: 3
  flame: 1
  infinity: 1
  luck_of_the_sea: 5
  lure: 5
  mending: 1